name: geopy2021a
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.19.*
  - dask
  - dask-core
  - datashader
  - xarray>=0.18
  - descartes>=1.1
  - earthpy=0.9.*
  - esda>=2.3
  - fiona=1.8.*
  - folium>=0.11
  - gdal>=3.1
  - geographiclib=1.*
  - geojson=2.5.*
  - geopandas>=0.8
  - geoplot=0.4.*
  - geopy>=2.1
  - geos>=3.8
  - geoviews>=1.8
  - hdf4=4.2.*
  - hdf5=1.*
  - holoviews>=1.13
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab
  - mapclassify>=2.3
  - matplotlib>=3.3
  - netcdf4=1.5.*
  - networkx>=2.5
  - notebook
  - numpy
  - osmnx=1.*
  - owslib>=0.23
  - pandas>=1
  - pillow
  - proj>=7.1
  - pyproj>=2.6.1.post1
  - pysal>=2.4
  - pytables=3.6.*
  - python=3.8
  - rasterio>=1.1
  - rasterstats>=0.14
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn=0.11.*
  - shapely=1.7.*
